# Generated by Django 4.2.17 on 2024-12-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_cart_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
