# Generated by Django 4.2.17 on 2024-12-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_images/', verbose_name='Фото блюда'),
        ),
    ]
