# Generated by Django 4.2.17 on 2024-12-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('image', models.ImageField(blank=True, upload_to='dish_images/', verbose_name='Лого')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_images/', verbose_name='Фото категории'),
        ),
    ]
