# Generated by Django 4.2.17 on 2024-12-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, default='default_images/default_foto.png', upload_to='dish_images/', verbose_name='Фото блюда'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, default='default_images/default_foto.png', upload_to='restaurant_images/', verbose_name='Лого'),
        ),
    ]
